### ISSUE TITLE
No module named 'xentropy_cuda_lib'

### ISSUE THREAD

**Issue by ajdotexecute** [jzhang38/TinyLlama#142]
I've been trying to install on Windows, encountered the rotary_emb issue #19 and used the solution stated there which fixed it but, but immediately encountered the no `xentropy_cuda_lib`
```

(tinyllama_env) E:\TinyLlama>python tinyllamachatbot.py
A matching Triton is not available, some optimizations will not be enabled.
Error caught was: No module named 'triton'
Traceback (most recent call last):
  File "E:\TinyLlama\tinyllamachatbot.py", line 1, in <module>
    from lit_gpt.model import Model
  File "E:\TinyLlama\lit_gpt\__init__.py", line 4, in <module>
    from lit_gpt.fused_cross_entropy import FusedCrossEntropyLoss
  File "E:\TinyLlama\lit_gpt\fused_cross_entropy.py", line 5, in <module>
    import xentropy_cuda_lib
ModuleNotFoundError: No module named 'xentropy_cuda_lib'
```

Please advise on how to solve this issue, and gove any tips on installing on windows.

**Comment by ChaosCodes** [comment]
Hi perhaps you need to install xentropy first:
```
git clone https://github.com/Dao-AILab/flash-attention
cd flash-attention
python setup.py install
cd ../xentropy && pip install .
cd ../.. && rm -rf flash-attention
```
