### ISSUE TITLE
Help me pls

### ISSUE THREAD

**Issue by aritralegndery** [jzhang38/TinyLlama#168]
```Traceback (most recent call last):   File "e:\llm\TinyLlama\pretrain\tinyllama.py", line 17, in <module>     from lit_gpt.model import GPT, Block, Config, CausalSelfAttention   File "E:\llm\TinyLlama\lit_gpt\__init__.py", line 1, in <module>     from lit_gpt.model import GPT   File "E:\llm\TinyLlama\lit_gpt\model.py", line 13, in <module>     from flash_attn import flash_attn_func ModuleNotFoundError: No module named 'flash_attn'```

**Comment by jzhang38** [comment]
Follow the instructions at https://github.com/Dao-AILab/flash-attention to install flash attn.

**Comment by aritralegndery** [comment]
> Follow the instructions at https://github.com/Dao-AILab/flash-attention to install flash attn.

Thank You Sir.

**Comment by lixali** [comment]
This is taking me a very long time to install. 6 hours now and it is still not finished. Is it normal?
